### ISSUE TITLE
LLDB never finishes importing Swift modules/setting up Swift reflection

### ISSUE THREAD

**Issue by z2oh** [swiftlang/llvm-project#8572]
<img width="338" alt="image" src="https://github.com/apple/llvm-project/assets/385684/50a55ff3-90b9-4b85-b4e2-a527d13ebc86">

These notifications in VS Code never go away during a debugging session. It's possible there's an issue on the client side, but I'm thinking the issue is in LLDB.

The `Progress` object which reports the reflection status is set up here: https://github.com/apple/llvm-project/blob/00c794fb25f1085c060d5c46e34cbb6145837f1f/lldb/source/Plugins/LanguageRuntime/Swift/SwiftLanguageRuntime.cpp#L505

This ctor takes an optional `total` parameter, which, as `Progress::increment` is called, is compared against to see when the operation is complete. When it's not set, the docs indicate [that an indeterminate progress indicator](https://github.com/apple/llvm-project/blob/00c794fb25f1085c060d5c46e34cbb6145837f1f/lldb/include/lldb/Core/Progress.h#L76-L78) should be displayed, but as far as I can tell, there's no way to report completion of this (which is normally triggered when `Progress::m_completed == Progress::m_total`).

It looks like the reflection progress object used to be constructed with a total, and with the following patch, I am no longer seeing the permanent "Setting up swift reflection" indicator:

```
diff --git a/lldb/source/Plugins/LanguageRuntime/Swift/SwiftLanguageRuntime.cpp b/lldb/source/Plugins/LanguageRuntime/Swift/SwiftLanguageRuntime.cpp
index 76a65ead7ff9..d3b83c784571 100644
--- a/lldb/source/Plugins/LanguageRuntime/Swift/SwiftLanguageRuntime.cpp
+++ b/lldb/source/Plugins/LanguageRuntime/Swift/SwiftLanguageRuntime.cpp
@@ -502,7 +502,7 @@ void SwiftLanguageRuntimeImpl::ProcessModulesToAdd() {

   auto &target = m_process.GetTarget();
   auto exe_module = target.GetExecutableModule();
-  Progress progress("Setting up Swift reflection");
+  Progress progress("Setting up Swift reflection", {}, modules_to_add_snapshot.GetSize());
   size_t completion = 0;

   // Add all defered modules to reflection context that were added to
```

The preferred total is less obvious for the "Importing Swift modules" progress events ([here](https://github.com/apple/llvm-project/blob/3cba3c783ca8712981734ee8ef7f2f56685a7a68/lldb/source/Plugins/TypeSystem/Swift/SwiftASTContext.cpp#L2137) and [here](https://github.com/apple/llvm-project/blob/3cba3c783ca8712981734ee8ef7f2f56685a7a68/lldb/source/Plugins/TypeSystem/Swift/SwiftASTContext.cpp#L2137)). Any ideas on what these totals should be?

cc @chelcassanova, it looks like you've been driving the improvements to the lldb reporting feature

**Comment by chelcassanova** [comment]
Hey Jeremy, thanks for tagging me in this and also for the patch! The "Setting up Swift reflection" report is indeed missing a total and your patch is correct, if you're able to put that patch up for review and add me as a reviewer that would be great 👍🏾 .

For the "Importing Swift modules" report, we actually have that as an indeterminate report so it doesn't have a total. The multiple reports you're seeing for "Importing Swift modules" is a bug that I'm looking into, thanks again for bringing this up!

**Comment by z2oh** [comment]
I appreciate you looking into this @chelcassanova! PR with the aforementioned patch is up here https://github.com/apple/llvm-project/pull/8584

(I don't think I have the right repo privileges to manually specify reviewers)

**Comment by chelcassanova** [comment]
Fixed in https://github.com/apple/llvm-project/pull/8623

**Comment by z2oh** [comment]
I finally got around to updating my Swift toolchain to a version which includes #8623, but I'm still seeing these persistent notifications when debugging a Swift project in VS Code:
<img width="339" alt="image" src="https://github.com/apple/llvm-project/assets/385684/b9d1f0b1-5a65-4f7e-a3b2-ff9edbcb5a38">

If I understand the `Progress` semantics correctly, completion is only signaled upon one of:
1) if a total was set in the constructor, when `Increment` reaches that total
2) `Progress` object destructor is run

If we don't know the number of modules up front, is there a way to clean up the `Progress` object once we've completed?

**Comment by z2oh** [comment]
cc @chelcassanova, I'll look into resolving this soon and would love to hear your thoughts before digging in!

**Comment by chelcassanova** [comment]
Hey Jeremy, so sorry for my late response and thanks for looking into this! The `Progress` destructor should get run once the object is out of scope due to RAII, and since we create the progress report for Swift imports through a callback we also clear that callback on scope exit.

One of the original reasons that those spurious reports were coming in was because we cleared the callback by creating a new `Progress` object which will print the message it was initialized with, so the patch I merged just cleared it to an empty function. Just curious, are all of those reports just showing up with a title and no details?

**Comment by z2oh** [comment]
> Just curious, are all of those reports just showing up with a title and no details?

Yes, as far as I can tell. Here's a screenshot from just now:

<img width="226" alt="image" src="https://github.com/apple/llvm-project/assets/385684/48873923-0f37-4eaa-9367-d063fad34819">

`swift --version` reports `compnerd.org Swift version 6.0-dev (LLVM 57177aa1b91540b, Swift 6debc331289f02d)`, and this includes #8623 (https://github.com/apple/llvm-project/commits/57177aa1b91540b).

I let this spin for quite a bit (10+ minutes) and never saw them go away, so I _assume_ that the `std::unique_ptr<Progress>` is being kept alive somehow, though I haven't confirmed this.

More than happy to provide as much detail as I can on this!

**Comment by chelcassanova** [comment]
The `unique_ptr` staying alive is also one of the main culprits I can think of, the other being that the reports are getting created but no details are being displayed which would indicate that the message that's supposed to get displayed with `progress->Increment` isn't being displayed at all, or that these reports are created but `progress->Increment` itself isn't being called so no details are added to the report. 🤔
